Iter9
adettelle/go-metric-collector pull request #10
Opened 2024-07-01 10:08 UTC by adettelle

2024-07-03 00:48 UTC, capsulated requested changes
Написал комментарии. Как обычно, если с чем-то не согласна или есть вопросы - можно добавлять аргументированный ответ на комментарий. Если много вопросов и непонятного - можно на 1-1 обсудить

2024-07-03 00:48 UTC, capsulated commented on cmd/server/main.go
> +	fi, err := os.Stat("/tmp/metrics-db.json")
Чтение файла в `cmd` не лучшее решение. Лучше независимый пакет для этого - самый удобный вариант. Либо, на крайний случай, пару методов в хранилке, но в следующих спринтах всё равно придётся их выносить

2024-07-03 00:48 UTC, capsulated commented on cmd/server/main.go
> +	fileStoragePath, err := os.Stat(config.StoragePath)
Да, всю работу с файлами инкапсулировать в пакет и "спрятать" все подробности реализации

2024-07-03 00:48 UTC, capsulated commented on cmd/server/main.go
> +	if config.Restore {
Явно надо передать конфиг в конструктор хранилки и в зависимости от конфига либо использовать файл, либо нет. В `cmd`  обычно инициализация и запуск приложения. Можно отдельный пакет создать для дампа в файл, и его передать хранилке и вызывать его методы

2024-07-03 00:48 UTC, capsulated commented on cmd/server/main.go
> +	log.Printf("Got termination signal: %s. Graceful shutdown", s)
Чтение канала есть, но обработки сигналов нет) Минимальный пример выглядит как-то так: https://gobyexample.com.ru/signals

2024-07-03 00:48 UTC, capsulated commented on internal/agent/metricservice/service.go
> +func NewMetricService(config *config.Config, metricStorage *mstore.MemStorage) *MetricService { // store StorageInterfase,
Это не критично, но кажется, что если уточнить, что за сервис, будет немного проще читать код: `Agent`, `MetricAgent`, `MetricSender`, `MetricHarvester`, `MetricCollector`, `MetricScraper`. А то при чтении не сразу понятно,  это сервис метрик клиентский или серверный))

2024-07-03 00:48 UTC, capsulated commented on internal/api/router.go
> +package api
В пакет `api` можно перенести все сущности, которые используются для реализации API. Тут можно расположить и хендлеры, и роутер, и сервер. Вот несколько вариантов:
```
> api
-- router.go
-- server.go
-- handlers.go
```

Либо создать пакеты, если сущность 'обрастает'  большим количеством методов, дополнительных типов и функций:
```
> api
--> handlers
----- create.go
----- get.go
----- update.go
----- value.go
-- router.go
-- server.go
```

2024-07-03 00:48 UTC, capsulated commented on internal/handlers/handlers.go
> +// type Storager interface {
Комментарии, обычно, не оставляют в PR

А кстати,  `Storage` подходящее имя для интерфейса. А реализации будут `MemStorage` / `FileStorage` и тп

2024-07-03 00:48 UTC, capsulated commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
А тут остановится выполнение метода в случае ошибки? Нужно проверить, и либо везде перепроверить что есть `return`, либо наоборот, веде убрать, если не нужен

2024-07-03 00:48 UTC, capsulated commented on internal/handlers/handlers.go
> +	return &MetricHandlers{
Это и есть DI - внедрение зависимостей. Удобно их внедрять через конструкторы: такой подход прибавляет 'гибкости' коду

2024-07-03 00:48 UTC, capsulated commented on internal/logger/logger.go
> +package logger
Логгер мтоже можно перенести в `pkg` в корне. Чтобы потом использовать в выпускном, к промеру

2024-07-03 00:48 UTC, capsulated commented on internal/logger/logger.go
> +type responseData struct {
Так, а это middleware, и из пакета логгера надо убрать, переместив именно в middleware. У chi хороший [пример](https://github.com/go-chi/chi/tree/master/middleware) реализации middleware. И их также можно перенести в `pkg`, чтобы импортировать в других проектах

2024-07-03 00:48 UTC, capsulated commented on internal/mware/mware.go
> +package mware
Лучше `middleware`. И из `internal` вынести

2024-07-03 00:48 UTC, capsulated commented on internal/mygzip/mygzip.go
> +package mygzip
`my-`  обычно в примерах обучающих используют, а для production такой нейминг не подойдёт). К примеру: `gzip`, `compressor`, `httpgzip`, `gzipwriter` или что-то подобное

2024-07-03 00:48 UTC, capsulated commented on internal/mygzip/mygzip.go
> +func (c compressReader) Read(p []byte) (n int, err error) {
И тут ресивер передаётся тип по значению? Почему не по указателю?

2024-07-03 21:52 UTC, adettelle commented on cmd/server/main.go
> +	fi, err := os.Stat("/tmp/metrics-db.json")
перенесла в конфиг

2024-07-03 21:53 UTC, adettelle commented on cmd/server/main.go
> +	fileStoragePath, err := os.Stat(config.StoragePath)
сделала

2024-07-03 21:53 UTC, adettelle commented on cmd/server/main.go
> +	if config.Restore {
готово

2024-07-03 21:54 UTC, adettelle commented on cmd/server/main.go
> +	log.Printf("Got termination signal: %s. Graceful shutdown", s)
поправила

2024-07-03 21:54 UTC, adettelle commented on internal/agent/metricservice/service.go
> +func NewMetricService(config *config.Config, metricStorage *mstore.MemStorage) *MetricService { // store StorageInterfase,
согласна, поменяла название

2024-07-03 21:55 UTC, adettelle commented on internal/api/router.go
> +package api
в итоге почистила всю структуру

2024-07-03 21:56 UTC, adettelle commented on internal/handlers/handlers.go
> +// type Storager interface {
понимаю, но пока, если я удалю все комментарии, опасаюсь запутаться. Решила в процессе обучения оставлять их в качестве самопомощи )))

2024-07-03 21:56 UTC, adettelle commented on internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
👍

2024-07-03 21:56 UTC, adettelle commented on internal/handlers/handlers.go
> +	return &MetricHandlers{
👍

2024-07-03 21:57 UTC, adettelle commented on internal/logger/logger.go
> +package logger
готово

2024-07-03 21:57 UTC, adettelle commented on internal/logger/logger.go
> +type responseData struct {
👍

2024-07-03 21:57 UTC, adettelle commented on internal/mygzip/mygzip.go
> +package mygzip
поправила

2024-07-03 21:58 UTC, adettelle commented on internal/mygzip/mygzip.go
> +func (c compressReader) Read(p []byte) (n int, err error) {
👍

2024-07-05 03:48 UTC, capsulated commented on internal/handlers/handlers.go
> +// type Storager interface {
👌

2024-07-05 04:02 UTC, capsulated approved these changes
Всё супер, все комментарии учтены 👍

Я оставил ещё парочку, они совсем не критичные, для сведения к следующему спринту

Апрувлю

2024-07-05 04:02 UTC, capsulated commented on cmd/server/main.go
> +	go startServer(config, ms)
Я бы не выносил в отдельную функцию, чтобы читать удобнее было:
```go
...
log.Println("config:", config)

fmt.Printf("Starting server on %s\n", config.Address)
api  := api.NewMetricHandlers(ms, config) // объект хэндлеров, ранее было handlers.NewMetricAPI(ms)
routes := api.NewMetricRouter(ms, mAPI)

go func(address string, routes *MetricRouter) {
	err := http.ListenAndServe(address, routes)
	if err != nil {
		log.Fatal(err)
	}
}(config.Address)
```
В таком виде всё "перед глазами", вся инициализация и запуск

2024-07-05 04:02 UTC, capsulated commented on internal/api/handlers.go
> +type MetricHandlers struct { // было MetricAPI
Супер! Единственное, тип и конструктор в начале описываются, а затем методы этого типа, для того, чтобы последовательно читать код

2024-07-05 15:26 UTC, adettelle commented on internal/api/handlers.go
> +type MetricHandlers struct { // было MetricAPI
👍не заметила, как они улетели вниз, поправила

2024-07-05 15:27 UTC, adettelle commented on cmd/server/main.go
> +	go startServer(config, ms)
👍

2024-07-19 10:58 UTC, merged