Iter13
adettelle/go-metric-collector pull request #14
Opened 2024-07-16 09:06 UTC by adettelle

2024-07-23 00:19 UTC, capsulated requested changes
Главная неразбериха - это использование memStrage в агенте, всё же лучше другую сущность созадть для этого. Комментарии оставил, если где-то непонятно - пиши в чат подгруппы, будем разбираться (либо 1-1 если необходимо)

2024-07-23 00:19 UTC, capsulated commented on cmd/agent/main.go
> +	metricsStorage, err := memstorage.New(false, "")
А почему именно хранилка в памяти  создаётся? У нас же интерфейс и хранилка создаётся в зависимости от конфига. И очень странная история, что хранилка используется и в агенте и в сервере 🤔 Что-то тут неправильно

В таком случае отлично походит паттерн `абстрактная фабрика`: во входящих параметрах условие (в нашем случае это конфиг), а на выходе - интерфейс:

```go
type Storage interface {
	Get(...) (...)
	Set(...) (...)
}

func NewStorage(cfg config.Storage) (Storage, error) {
   if (...) {
      return NewDbStorage(...)
   }
   
   if (...) {
      return NewMemStorage(...)
   }
   
   return NewFileStorage(...)
}
```

И уже зависимость на хранилку передаём через интерфейс (в конструктор воркера или хендлеров)

2024-07-23 00:19 UTC, capsulated commented on cmd/agent/main.go
> +	metricsStorage, err := memstorage.New(false, "")
Локально метрики хранить (на уровне пакета или метода) лучше в поле структуры или в локальной переменной. А хранилку в памяти использовать строго на основе интерфейса, без возможности чтения полей экземпляра хранилки (если необходимо, то добавляются новые методы в интерфейс геттеры/сеттеры для получения/записи этих полей)

2024-07-23 00:19 UTC, capsulated commented on internal/agent/metricservice/service.go
> +	for name, value := range ms.metricStorage.Gauge {
Вот. Нельзя напрямую обращаться к полю хранилки, так как нам хранилку надо начинать передавать через интерфейс. Должен быть метод в интерфейсе:
```go
type Storage interface {
    GetAllGuages(...) (...)
    GetCounters(...) (...)
}
```

2024-07-23 00:19 UTC, capsulated commented on internal/agent/metricservice/service.go
> +func doSend(url string, data *bytes.Buffer) error {
Это всё же надо методом сервиса сделать, слишком сильно он связан с обласью ответственности сервиса. А в конструкторе сервиса ещё хорошо бы создать экземпляр своего клиента (не DefaultClient) для запросов

2024-07-23 00:19 UTC, capsulated commented on internal/agent/metricservice/service.go
> +		for i := 0; i < 4; i++ {
Может как-то в метод обернуть? И в конфиг ещё можно добавить поле с количетсовм попыток для ретрая

2024-07-23 00:19 UTC, capsulated commented on internal/agent/metricservice/service.go
> +func (ms *MetricCollector) SendLoop(delay time.Duration, wg *sync.WaitGroup) {
Ресивер `ms` а имя типа - `MetrciCollector`, наверное тогда  `mc`?

2024-07-23 00:19 UTC, capsulated commented on internal/api/handlers.go
> +type Storager interface {
А, ну вот интерфейс. memStorage реализует же этот интерфейс? Соответственно, надо использовать эти методы, без обращения к полям структуры напрямую

2024-07-23 00:19 UTC, capsulated commented on internal/db/db.go
> +func connect(dbParams string) (*sql.DB, error) {
Так, эту функцию надо сделать методом для структуры хранилки БД. Подключение к БД удобно в конструкторе реализовывать

2024-07-23 00:19 UTC, capsulated commented on internal/db/db.go
> +func ConnectWithRerties(dbParams string) (*sql.DB, error) {
Ретраи, если получиться, вообще в отдельный пакет вынести. Если не получиться универсальный сделать, то можно для каждого типа свои типы или простые функции добавить. 

Ретраи были в задании, но вообще они полезны для запросов на сторонние API или какие-то нестабильные SaaS сервисы, а для собственных API или БД - это избыточно (для справки)

2024-07-23 00:19 UTC, capsulated commented on internal/storage/dbstorage/dbstorage.go
> +func (dbstorage *DBStorage) GetGaugeMetric(name string) (float64, bool, error) {
Ресивер лучше одной буквой сокращать, а остальные имена локальных переменных уже от трёх символов (или вообще не сокращать). Это для того, чтобы в коде ресивер сразу найти можно было

2024-07-23 00:19 UTC, capsulated commented on internal/storage/dbstorage/dbstorage.go
> +		sqlStatement := "insert into metric (metric_type, metric_id, value)" +
Можно же INSERT ... ON CONFLICT запрос написать, чтобы if небыло и дополнительного получения метрики. И транзакции тоже не будет, если один запрос останется. Лучше их минимизировать

2024-07-23 00:19 UTC, capsulated commented on internal/storage/dbstorage/dbstorage.go
> +	if !ok {
тут также (ON CONFLICT psql)

2024-07-23 00:19 UTC, capsulated commented on internal/storage/memstorage/filestorage.go
> +func WriteMetricsSnapshot(fileName string, ms *MemStorage) error {
Можно сделать дополнительную структуру создать с методами создания  и чтения данных в файл. И передать его в конструктор хранилки.

2024-07-23 00:19 UTC, capsulated commented on pkg/gzipcompressor.go
> +func NewCompressWriter(w http.ResponseWriter) *compressWriter {
Отдельный пакет создать надо бы compressor, к примеру. А то как-то странно он прям в pkg лежит

2024-07-24 15:59 UTC, adettelle commented on cmd/agent/main.go
> +	metricsStorage, err := memstorage.New(false, "")
memStorage обладает одинаковым поведением и в агенте, и в сервере, он аккумулирует метрики. Если создавать другой storage в агенте, он будет почти полностью дублировать memStorage из сервера, там одна и та же логика. Я подумала, что не надо плодить сущности. 
В агенте я просто аккумулирую метрики между отправками на сервер, есть логика суммирования counter метрик и перезаписи gauge метрик. Далее они отправляются и storage очищается. 
В сервере же я просто сохраняю их там по мере дерганья ручки. И как раз только в сервере есть конфиг на выбор места хранения: storage, БД или файл. У агента такого естественно нет.
Абстрактную фабрику применила, готово.

2024-07-24 16:00 UTC, adettelle commented on internal/agent/metricservice/service.go
> +	for name, value := range ms.metricStorage.Gauge {
Поправила, готово

2024-07-24 16:00 UTC, adettelle commented on internal/agent/metricservice/service.go
> +func doSend(url string, data *bytes.Buffer) error {
готово

2024-07-24 16:01 UTC, adettelle commented on internal/agent/metricservice/service.go
> +		for i := 0; i < 4; i++ {
сделала

2024-07-24 16:01 UTC, adettelle commented on internal/agent/metricservice/service.go
> +func (ms *MetricCollector) SendLoop(delay time.Duration, wg *sync.WaitGroup) {
это был след от старого названия, исправила

2024-07-24 16:02 UTC, adettelle commented on internal/api/handlers.go
> +type Storager interface {
ок

2024-07-24 16:03 UTC, adettelle commented on internal/db/db.go
> +func connect(dbParams string) (*sql.DB, error) {
DBStorage - это же репозиторий. Его задача заниматься тем, чтобы манипулировать объектами БД. Подключение и создание таблиц — это вне зоны его ответственности кажется.

2024-07-24 16:03 UTC, adettelle commented on internal/db/db.go
> +func ConnectWithRerties(dbParams string) (*sql.DB, error) {
Спасибо, оставлю пока на будущее

2024-07-24 16:05 UTC, adettelle commented on internal/storage/dbstorage/dbstorage.go
> +func (dbstorage *DBStorage) GetGaugeMetric(name string) (float64, bool, error) {
готово

2024-07-24 16:05 UTC, adettelle commented on internal/storage/dbstorage/dbstorage.go
> +		sqlStatement := "insert into metric (metric_type, metric_id, value)" +
готово

2024-07-24 16:05 UTC, adettelle commented on internal/storage/memstorage/filestorage.go
> +func WriteMetricsSnapshot(fileName string, ms *MemStorage) error {
Идея понятна, если можно, пусть это уйдет в мой тех долг.

2024-07-24 16:06 UTC, adettelle commented on pkg/gzipcompressor.go
> +func NewCompressWriter(w http.ResponseWriter) *compressWriter {
готово

2024-07-26 01:59 UTC, capsulated approved these changes
Оставил два комментария.

Про ретраи, больше для примера, если будет время. Апрувлю, но про memstorage это важный момент, если останутся вопросы то 1-1, без камеры вообще не проблема, но главное экран чтобы можно было расшарить

2024-07-26 01:59 UTC, capsulated commented on cmd/agent/main.go
> +	metricsStorage, err := memstorage.New(false, "")
Это уже не `storage`, это `state`. `Storage` хранит персистентные данные, а `state` - данные текущего  состояния (state'а). У нас, конечно, хранилка в памяти, но она имитирует реальное хранилище. Объекты лучше создавать для области ответственности, а в нашем случае получается что хранилка со стороны сервера будет накапливать данные, а со стороны агента хранить текущее состояние

2024-07-26 01:59 UTC, capsulated commented on internal/agent/metricservice/service.go
> +		for i := 0; i < 4; i++ {
Ну ок) Но можно, кстати, расширить клиент и в нём ретраи реализовать. В  следующем спринте предлагаю попробовать)

2024-07-26 01:59 UTC, capsulated commented on internal/storage/memstorage/filestorage.go
> +func WriteMetricsSnapshot(fileName string, ms *MemStorage) error {
Ок, принимается))

2024-07-26 10:35 UTC, merged