Iter23
adettelle/go-metric-collector pull request #24
Opened 2024-10-22 16:17 UTC by adettelle

2024-10-22 16:20 UTC, adettelle commented
в readme написала, как создавать сертификаты и запускать с ними

2024-10-23 22:41 UTC, capsulated requested changes
Очень странная конструкция у агента: запускается сервер на 9000 порту - главный вопрос по ревью, пиши тогда в директ в пачку, чтобы поскорее заапрувить

А если контекст получится запилить - было бы круто, но если не успеешь - тогда todo обязательно оставить надо)

Остальное всё отлично

2024-10-23 22:41 UTC, capsulated commented on cmd/agent/main.go
> +		if err = http.ListenAndServe(":9000", nil); err != nil {
А тут зачем агенту http сервер на 9000 порту?

2024-10-23 22:41 UTC, capsulated commented on cmd/cert/cert.go
> +func main() {
Ключи для таких целей обычно не создаются собственноручно, так как полно готовых консольных программ для генерации. Это скорее для образовательных целей

2024-10-23 22:41 UTC, capsulated commented on internal/agent/metricservice/service.go
> +func (ms *MetricService) SendLoop(delay time.Duration, wg *sync.WaitGroup, term <-chan struct{}) error {
Также, контекст в данном случае самое то, так как контекст с отменой это и есть канал с пустым интерфейсом - можно посмотреть реализацию в исходниках

2024-10-23 22:41 UTC, capsulated commented on internal/agent/metricservice/service.go
> +outer:
Ох, лучше не использовать метки, на любом собесе не обрадуется такому решению

2024-10-23 22:41 UTC, capsulated commented on internal/agent/metricservice/service.go
> +	// for range ticker.C {
Комменты комитить в MR - плохая практика, так как читаемость кода ухудшается (так жде как и у меток с goto)

2024-10-24 10:50 UTC, adettelle commented on cmd/agent/main.go
> +		if err = http.ListenAndServe(":9000", nil); err != nil {
это было задание инкремента 16 по профилировщику, надо было стартануть сервер, чтобы профилировщик мог зарегистрироваться. если это стоит уже удалить, я конечно его уберу.

2024-10-24 10:51 UTC, adettelle commented on internal/agent/metricservice/service.go
> +func (ms *MetricService) SendLoop(delay time.Duration, wg *sync.WaitGroup, term <-chan struct{}) error {
готово

2024-10-25 09:52 UTC, capsulated approved these changes
Всё хорошо, но метки (goto) обязательно убрать в следующем спринте, и комментарии лишние почистить

2024-10-25 10:51 UTC, merged