Iter25
adettelle/go-metric-collector pull request #29
Opened 2024-10-28 19:35 UTC by adettelle

2024-10-28 20:39 UTC, adettelle commented
привет! добавила в readme запуск с возможностью использования grpc

2024-10-31 02:14 UTC, capsulated requested changes
В принципе, всё отлично, но покрытие тестами надо бы увеличтиь) В введении к спринте очень хитро  указано `важное условие: к концу спринта ваш код должен быть покрыт тестами на 80%.`

Также, добавил пару коментариев

2024-10-31 02:14 UTC, capsulated commented on internal/grpcserver/grpcserver.go
> +type MServer struct {
В данном случае, нейминг `GrpcServer` более подходящий, по аналогии с `PostgresStorage`. Или это что-то другое?

2024-11-05 15:37 UTC, adettelle commented on internal/grpcserver/grpcserver.go
> +type MServer struct {
поправила

2024-11-05 15:38 UTC, adettelle commented
добавила тестов, в readme написала команду к покрытию

2024-11-08 00:51 UTC, capsulated approved these changes
Всё отлично 👍

Поздравляю с завершением кодовых инкрементов! 🥳 Проделана большая работа 🦾

Будут вопросы, пиши напрямую в директ пачки, особенно по выпускной

2025-11-17 12:40 UTC, merged