Iter5
adettelle/go-metric-collector pull request #6
Opened 2024-06-09 20:03 UTC by adettelle

2024-06-12 19:43 UTC, capsulated requested changes
Коменты добавил, они в общей сложности по структуре приложения. С логикой всё приложения всё ок

2024-06-12 19:43 UTC, capsulated commented on metricstest
Бинарники в репозиторий не комитят, надо удалить

2024-06-12 19:43 UTC, capsulated commented on cmd/agent/main.go
> +func sendMetric(addr string, metricType string, name string, value float64) error {
Функционал сбора/отправки метрик необходимо переместить в отдельный пакет воркер/сервис. В `cmd` должна быть конфигурация и запуск приложения

2024-06-12 19:43 UTC, capsulated commented on cmd/agent/main.go
> +			return err
Если одна метрика не отправиться, то все оставшиеся (не отправленные) также не будут отправлены?

2024-06-12 19:43 UTC, capsulated commented on cmd/agent/main.go
> +func main() {
Думаю, в `cmd` должно остаться только это

2024-06-12 19:43 UTC, capsulated commented on cmd/server/main.go
> +type NetAddress struct {
Для этого можно также отдельный пакет создать, к примеру `config`

2024-06-12 19:43 UTC, capsulated commented on cmd/server/main.go
> +	r.Post("/update/{metric_type}/{metric_name}/{metric_value}", mAPI.CreateMetric)
Роутер также, отдельный пакет для роутера и хендлеров, либо даже различные пакеты для роутера и хенделра. Но из `cmd` точно необходимо переместить

2024-06-12 19:43 UTC, capsulated commented on internal/agent/config.go
> +type Config struct {
А конфиг есть, оказывается. Можно создать отдельный конфиг для сервера. В первых инкрементах он будет совсем небольшой, но в следующих инкрементах увеличится в объёме

2024-06-12 19:43 UTC, capsulated commented on internal/handlers/handlers.go
> +func (metricAPI *MetricAPI) CreateMetric(w http.ResponseWriter, r *http.Request) {
Нейминг ресивера (указателя на экземпляр структуры) принято записывать сокращённо по первой/первым символам в имени, чтобы в коде было понятно, что это указатель на экземпляр (аналог this или self в других языках): `m` или `ma`. 

PS И обязательно разобраться: использовать по указателю или значению? И почему)

2024-06-12 19:43 UTC, capsulated commented on internal/server/config.go
> +func NewConfig() (*Config, error) {
Так как имя структурного типа Config совпадает с именем пакета, то принято именовать конструктор просто
```go
func New() (*Config, error) ...
```

2024-06-12 19:43 UTC, capsulated commented on internal/storage/maprepository.go
> +func (ms *MemStorage) GetAllMetric(w io.Writer) {
Можно уточнить нейминг немного, что это html-template, что-то типа `GetHtmlMetrics` или что-то подобное

2024-06-12 19:43 UTC, capsulated commented on internal/storage/maprepository.go
> +type Storage interface {
Имена интерфейсв принято именовать с -er постфиксом:`Storager` https://go.dev/doc/effective_go#interface-names

А описывать в месте, где он используется (а не в месте реализации)

2024-06-13 12:37 UTC, adettelle commented on metricstest
случайно попал, готово

2024-06-13 14:24 UTC, adettelle commented on cmd/agent/main.go
> +func sendMetric(addr string, metricType string, name string, value float64) error {
поправила

2024-06-13 14:25 UTC, adettelle commented on cmd/agent/main.go
> +			return err
да, было так. поправила логику

2024-06-13 14:25 UTC, adettelle commented on cmd/agent/main.go
> +func main() {
готово

2024-06-13 14:26 UTC, adettelle commented on cmd/server/main.go
> +type NetAddress struct {
это лишний кусок кода, убрала. config есть

2024-06-13 14:26 UTC, adettelle commented on internal/agent/config.go
> +type Config struct {
и для сервера тоже есть

2024-06-13 14:27 UTC, adettelle commented on internal/handlers/handlers.go
> +func (metricAPI *MetricAPI) CreateMetric(w http.ResponseWriter, r *http.Request) {
поправила нейминг, не могу никак привыкнуть у однобуквенным названиям )

2024-06-13 14:28 UTC, adettelle commented on internal/server/config.go
> +func NewConfig() (*Config, error) {
поправила

2024-06-13 14:28 UTC, adettelle commented on internal/storage/maprepository.go
> +func (ms *MemStorage) GetAllMetric(w io.Writer) {
готово

2024-06-13 14:28 UTC, adettelle commented on internal/storage/maprepository.go
> +type Storage interface {
готово

2024-06-13 15:01 UTC, adettelle commented on internal/storage/maprepository.go
> +type Storage interface {
перечитала статью и решила назвать StorageInterface, у меня же не один метод в интерфейсе. перенесла👍

2024-06-15 13:38 UTC, capsulated requested changes
Всё классно!
Но есть ошибка, с WaitGroup - её обязательно надо исправить, а остальные комментарии можно уже в следующем спринте

2024-06-15 13:38 UTC, capsulated commented on cmd/agent/main.go
> +// POLLINTERVAL=2 REPORTINTERVAL=10 go run ./cmd/agent/
Это лучше в README.md перенести, как инструкция к запуску. Можно godoc добавлять, но это будет в одном из последних спринтов

2024-06-15 13:38 UTC, capsulated commented on cmd/agent/main.go
> +	wg.Add(1)
Да, теперь намного лучше. Только вопрос по WaitGroup: ведь две го-рутины запускаются, а `wg.Add(1)` только один, а нужен `wg.Add(2)`, так как две го-рутины  и вызов `wg.Done()` два раза. Но примитивы синхронизации будем проходить в следующих спринтах. 

Лучше максимально простой способ выбрать, без доп усложнений

2024-06-15 13:38 UTC, capsulated commented on cmd/agent/main.go
> +	go metricservice.SendLoop(time.Duration(config.ReportInterval), metricsStorage, config.Address)
👍👍

2024-06-15 13:38 UTC, capsulated commented on internal/agent/metricservice/service.go
> +func sendMetric(addr string, metricType string, name string, value float64) error {
Функции в go можно также преобразовывать в методы типа. В итоге будет аналог классов других языков. Пример:
```go
type MemStorage struct { .... }

func NewMemStorgage(...)  { ... }
func (ms *MemStorage) Create(key string, val string) error { ... }
func (ms *MemStorage) Read(key string) ([]string, error) { ... }

// -------
// Сервисный слой
type MetricService struct {
   config *Config
   store Storer,
}

type Storer interface {
   Create(key string, val string) error
   Read(key string) ([]string, error)
}

func NewMetricService(config *Config, store Storer) *MetricService {
   ...
   return &MetricService{
      config : config ,
      store: store
   }
}

func (m *MetricService) sendMetric(...) error { ... }
   m.store.Read(...)
   println(m.config.Addr)
   ...
}

func (m *MetricService) sendAllMetrics(...) error { ... }
   m.store.Read(...)
   ...
}
```

В следующем спринте можно прийти к таким объектам, там, где необходимо. Удобно внедрять зависимости на другие объекты чероез конструкторы New, а не в передавать в параметры каждой функции

2024-06-15 13:38 UTC, capsulated commented on internal/handlers/handlers.go
> +type StorageInterface interface {
👍

Но интерфейсы именуются с постфиксом `-er` по [рекомендации комьюнити ](https://go.dev/doc/effective_go#interface-names). К примеру, `Storager`

2024-06-15 13:38 UTC, capsulated commented on internal/handlers/handlers.go
> +func NewMetricAPI(storage StorageInterface) *MetricAPI {
Позднее, можно будет в конструктор передавать ссылки на другие объекты: логгер, другие сервисы, трассировка и тп

2024-06-15 13:38 UTC, capsulated commented on internal/storage/memstorage/memstorage.go
> +func (ms *MemStorage) WriteMetricsReport(w io.Writer) {
Кстати, этот метод всё же из хранилки надо перенести в серисный слой, так как формирование html к хранилке не относится

2024-06-16 19:43 UTC, adettelle commented on cmd/agent/main.go
> +// POLLINTERVAL=2 REPORTINTERVAL=10 go run ./cmd/agent/
ok

2024-06-16 19:43 UTC, adettelle commented on cmd/agent/main.go
> +	wg.Add(1)
👍

2024-06-16 19:44 UTC, adettelle commented on internal/handlers/handlers.go
> +type StorageInterface interface {
исправила

2024-06-16 19:57 UTC, adettelle commented on internal/agent/metricservice/service.go
> +func sendMetric(addr string, metricType string, name string, value float64) error {
ок, это я тогда сделаю в следующем спринте

2024-06-16 20:00 UTC, adettelle commented on internal/storage/memstorage/memstorage.go
> +func (ms *MemStorage) WriteMetricsReport(w io.Writer) {
ок, это я тогда сделаю в следующем спринте

2024-06-17 20:23 UTC, capsulated commented on internal/handlers/handlers.go
> +type StorageInterfacer interface {
`StorageInterfacer` уже перебор, нужно что-то одно, либо `StorageInterface` или `Storager`. Я вообще с -ing пишу в пет проектах, тогда будет `Storing` )) 

Можно `Storage` оставить, если с комьюнити пример брать, главное названия выбирать однозначно, тогда будет успех))) Всё это очень абстрактно

2024-06-17 20:23 UTC, capsulated commented on cmd/server/main.go
> +	r.Post("/update/{metric_type}/{metric_name}/{metric_value}", mAPI.CreateMetric)
Решила не переносить? В принципе, не критично для проекта нашего курса, но в проектах, который будет развиваться пару лет, лучше подготавливать структуру в незавихмых пакетах / типах. Можно, например, создать один пакет `api` описанием структурных типов с конструкторами: `Handler`, `Router`, `Server`, всё что связано с сервером, а в нём файлы с этими объектами.

В любом случае, в следующих спринтах можно будет рефакторить, если захочется оптимизировать структуру приложения

2024-06-17 20:23 UTC, capsulated commented on internal/handlers/handlers.go
> +func (metricAPI *MetricAPI) CreateMetric(w http.ResponseWriter, r *http.Request) {
=))))) лучше однобуквенным только ресивер оставлять. А параметры метода - скоращённо.  Это собственный опыт, правил таких нет

2024-06-17 20:26 UTC, capsulated commented on internal/storage/maprepository.go
> +type Storage interface {
Ааа, это опечатка)))) В коде `StorageInterfacer`. Тогда все интерфейсы в рамках проекта должны быть с таким постфиксом `-Interface`. Интерфейсы с одним методом - это чаще нужно на уровне разработки библиотек для `go` или сами сорсы `go` доработать)

2024-06-17 20:32 UTC, capsulated approved these changes
Всё классно. Добавил пару комментов, больше для ознакомления перед след спринтом

2024-06-18 09:57 UTC, adettelle commented on internal/handlers/handlers.go
> +type StorageInterfacer interface {
не знаю, что на меня нашло, всё как в тумане )))
исправлю конечно

2024-06-18 09:59 UTC, adettelle commented
спасибо за развёрнутое ревью, все долги постараюсь закрыть в новом спринте, чтобы не тащить их дальше

2024-06-18 09:59 UTC, adettelle commented
👍

2024-06-18 10:03 UTC, merged